### ISSUE TITLE
popup 来个左右对齐？

### ISSUE THREAD

**Issue by kinglisky** [ywwhack/bdi-ui#1]
![image](https://user-images.githubusercontent.com/15852576/39621606-f6ae546a-4fc1-11e8-8f40-a9593bd5fa7f.png)

popup 出的弹窗不做个左对齐或者是右对齐吗？ popup 对齐到中间的话当筛选组件位于页面左边或者右边 popup 弹出会被挡住吧？

**Comment by ywwhack** [comment]
@kinglisky 考虑到大数据后面的项目基本都会用 element-ui，所以这里 popup 直接用的 element-ui 里的 dropdown 组件，它们已经处理的很好了

**Comment by kinglisky** [comment]
![](https://i.loli.net/2018/05/05/5aed77010c2e3.jpg)
